### ISSUE TITLE
Install on Amlogic S905 tv box running LibreElec

### ISSUE THREAD

**Issue by siliconhippy** [my-devices/sdk#4]
Nice project...

This could be great to access TV boxes, a big market. I am running LibreElec.tv on my Amlogic S905 TV box and the problem is that LibreElec is a read only Linux JeOS ( just enough OS) for media player KODI.

However LibreElec can install the Entware opkg package manager. So how can I install your build via Entware?

Cheers,
😁

**Comment by obiltschnig** [comment]
You'll have to build an opkg using an appropriate version of the Entware toolchain. Looks like Entware is based on OpenWRT. I plan provide OpenWRT package metadata in the next couple of days - this should then also work with Entware. Unfortunately, I cannot provide builds for all the different platforms (and versions) out there - there are just too many.

**Comment by siliconhippy** [comment]
I understand. So I will wait for your openwrt release...
