### ISSUE TITLE
SDK build failed

### ISSUE THREAD

**Issue by vishakam14** [my-devices/sdk#5]
Getting a "cannot find -lz" followed by bSDK build failed error while running ./buildsdk.sh command

**Comment by obiltschnig** [comment]
Depending on your platform and version of OpenSSL, you may have to remove the `-lz` flag from the line 
```
SYSLIBS += -lssl -lcrypto -lz -ldl
```
in `WebTunnel/*/Makefile`.

**Comment by vishakam14** [comment]
Worked, thanks.
