### ISSUE TITLE
configuring the device

### ISSUE THREAD

**Issue by vishakam14** [my-devices/sdk#6]
I am following the steps in this link https://macchina.io/blog/internet-of-things/how-to-access-and-control-your-thing-remotely-and-securely/.  I got my SDK to build and finished configuring the device. 
When I run ./bin/Linux/armv7l/WebTunnelAgent command, I get no such file/directory.
Is there a particular way to run this command?  Or am I missing a step here?

**Comment by obiltschnig** [comment]
First, make sure that building the SDK was successful. 
Then, the exact location of the `WebTunnelAgent` executable depends on your platform. On a Raspberry PI and many other ARM-based platforms, it will be in the `bin/Linux/armv7l` directory. On a 64-bit Intel platform it will be in `bin/Linux/x86_64`. So you have to specify the correct directory when starting `WebTunnelAgent`.

**Comment by vishakam14** [comment]
SDK building was successful.
I tried the Linux/x86_64 and I get Not found : webtunnel.reflectorURI

**Comment by obiltschnig** [comment]
Then you need the configuration file (`WebTunnelAgent.properties`). It must be located in the same directory as `WebTunnelAgent` executable, or in a parent directory. Follow the steps described under "Configuring the Device for Remote Access" in the mentioned article to generate one.

**Comment by vishakam14** [comment]
When I try to run WebTunnelAgent, I get a "cannot connect to reflector at "https://reflector.my-devices.net:WebSocket Exception:Not authorized" repeatedly.

**Comment by obiltschnig** [comment]
Show your `WebTunnelAgent.properties` file please.

**Comment by vishakam14** [comment]
[WebTunnelAgent.zip](https://github.com/my-devices/sdk/files/3019168/WebTunnelAgent.zip)

**Comment by obiltschnig** [comment]
I see nothing wrong here; the file also works for me. It looks your device is not even connecting to the reflector server. Could you try again? I have enabled logging on the server. Could you enable debug logging on `WebTunnelAgent`? You do this by editing `WebTunnelAgent.properties` and changing the setting `logging.loggers.root.level` from `notice` to `debug`:

```
logging.loggers.root.level = debug
```

**Comment by vishakam14** [comment]
Tried that, got:
Application<1>: Will reconnent in 9.27 seconds.
<Application<1>: Aborting HttpClientSession..
<Application<1>: Notifying disconnected status
<Application<1>: Disconnected.
<Application<1>:  Connecting to "https://reflector.my-devices.net..
<Application<1>: Creating WebSocket..
<Application<1>: "Cannot connect to reflector at "https://reflector.my-devices.net: WebSocket Exception:Not authorized

**Comment by obiltschnig** [comment]
It seems that your device is not actually connecting to `reflector.my-devices.net`. Could you do a 
`nslookup reflector.my-devices.net` and show me the output? The IP address should be `23.253.201.137`.

**Comment by vishakam14** [comment]
Got : Non-authoritative answer: Name: reflector.my-devices.net
Address: 23.253.201.137

**Comment by obiltschnig** [comment]
You did run `nslookup` on the device running `WebTunnelAgent`?
What happens if you run `curl -v https://reflector.my-devices.net` on your device?

**Comment by vishakam14** [comment]
Yes. 
![console](https://user-images.githubusercontent.com/22876104/55179068-b8244c00-5154-11e9-86a4-ade4a63fa530.jpg)

**Comment by obiltschnig** [comment]
Hmm, looks good. Please start `WebTunnelAgent` again.

**Comment by vishakam14** [comment]
Getting the same exception. The first time I ran it, I got a successful connection but when I checked my portal, it said the device was offline so I tried running it again and Ive been getting this exception.

**Comment by obiltschnig** [comment]
OK, I found something. Looks like you've changed the domain ID in your configuration.
I see a device in the server database with ID `c9eebed5-8705-4763-8822-b2616e736c13` and domain `ae379b89-22fb-4ef3-b221-92b22clb28a`, connected today at 15:43:13 UTC. 
Whereas the domain in the `WebTunnelAgent.properties` you've sent me is `ae379b89-22fb-4ef3-b221-92b228c1b28a`. Note the difference between `lb28a` and `1b28a`. This explains the `Not authorized` error - you are not allowed to connect with a different domain than the one it registered first.
I have deleted the device in the `lb28a` domain. Please try reconnecting again.

**Comment by vishakam14** [comment]
My bad, thank you ! I tried again and got it to establish a connection. But when I click on the device on my portal, I get "[Error] WebTunnel.RemotePortForwarded: Failed to open channel for port 80: Connection refused".

**Comment by obiltschnig** [comment]
That means no web server is running on your device on port 80.

**Comment by vishakam14** [comment]
Thank you so much for you assistance.
