### ISSUE TITLE
SSH 

### ISSUE THREAD

**Issue by vishakam14** [my-devices/sdk#7]
I was able to get my remote connection going, but I was wondering if it were possible to SSH into them. According to the FAQ, I am suppose to run WebTunnelAgent on the client. I am trying to run the Windows 10 SDK but I get a "Not found: webTunnel.reflectorURI".  I would really appreciate if I could get some guidance on this. Thanks.

**Comment by obiltschnig** [comment]
On the client side you need to run the `WebTunnelSSH` executable which is built as part of the SDK. See [here](https://macchina.io/remote_faq.html#ssh) for instructions. On a Windows system you also need a SSH client like PuTTY in addition to `WebTunnelSSH`. `WebTunnelSSH` first opens a tunnel connection to the device, then starts a SSH client (PyTTY) over that tunnel.

**Comment by vishakam14** [comment]
Yes, I did download the Windows SDK and tried running it, but it wouldn't run. So I tried running the exe through developers console and got the above exception.

**Comment by vishakam14** [comment]
Basically I am unable to run the remote manager executable.

**Comment by obiltschnig** [comment]
You must be doing something wrong here. If you start `WebTunnelSSH` without arguments, it will print a help screen. It will never print `Not found: webTunnel.reflectorURI`, this only ever comes from `WebTunnelAgent`. `WebTunnelSSH` does not need a configuration file usually. What you will need on Windows is PuTTY as SSH client. `putty.exe` must be in `%PATH`.

Here's what I did: after building the SDK using the solution file, you open a Command window and `cd` to `sdk\WebTunnel\WebTunnelSSH`. Then add `putty.exe` to the search path:
```
P:\git\my-devices\sdk\WebTunnel\WebTunnelSSH>set PATH=%PATH%;C:\putty\bin
```
On my system, `putty.exe` is in `C:\putty\bin`; you can usually put it wherever you like.
Then, start `WebTunnelSSH` and pass in the URL of your device (the link under the device name on the Remote Manager Dashboard, e.g. `https://4e142cab-e645-12e5-9a53-000db93012c0.my-devices.net/`). Optionally, you can specify the SSH login name (`pi` in my example, as I'm connecting to a Raspberry Pi):
```
P:\git\my-devices\sdk\WebTunnel\WebTunnelSSH>bin\static_mt\WebTunnelSSH.exe https://4e142cab-e645-12e5-9a53-000db93012c0.my-devices.net/ /login=pi
Remote Manager Username: user
Remote Manager Password:
```
You will be asked for your Remote Manager username and password.
After that, PuTTY will launch and you can log-in via SSH to your device.

**Comment by vishakam14** [comment]
I understand. What I am trying to say is when I download the Remote manager SDK from this link https://macchina.io/remote_downloads.html#sdk, I am unable to run the executable on my Windows. I guess the WenTunnelSSH is part of the remote manager SDK in the link. But I am not able to run the executable from that link.

**Comment by obiltschnig** [comment]
You'll have to build the SDK on Windows to get `WebTunnelSSH`. You can also download `WebTunnelSSH.exe` from [here](https://www.my-devices.net/download/WebTunnelClient/windows/AMD64/WebTunnelSSH.exe).

**Comment by vishakam14** [comment]
I downloaded the exe and tried running it, nothing happens. Is there a way to run this?

**Comment by obiltschnig** [comment]
As I said [here](https://github.com/my-devices/sdk/issues/7#issuecomment-479083167), you have to run it from a command prompt and provide some arguments.

**Comment by vishakam14** [comment]
![IMG-0331](https://user-images.githubusercontent.com/22876104/55424506-074bf180-5546-11e9-8d60-b9bf9fcea697.JPG)

**Comment by vishakam14** [comment]
Got it to work. Sorry for the trouble, Thank you.
